const PORTFOLIO_STATE = {
  "ticker_list": [
    "BTC-USD",
    "ETH-USD",
    "SOL-USD",
    "BNB-USD",
    "AVAX-USD",
    "LINK-USD",
    "ADA-USD",
    "XRP-USD",
    "DOT-USD",
    "DOGE-USD",
    "SUI20947-USD",
    "NEAR-USD",
    "LTC-USD",
    "TRX-USD",
    "OP-USD",
    "INJ-USD",
    "BCH-USD",
    "SHIB-USD",
    "WIF-USD",
    "ONDO-USD",
    "FET-USD",
    "RENDER-USD",
    "TON11419-USD",
    "PEPE24478-USD",
    "TAO22974-USD",
    "FTM-USD",
    "WLD-USD",
    "APT-USD",
    "TIA-USD",
    "RUNE-USD",
    "JUP29210-USD",
    "LDO-USD"
  ],
  "initial_capital": 32.33,
  "final_value": 14.0735101,
  "return_pct": -0.5646919239096814,
  "benchmark_return_pct": 0.0,
  "max_drawdown": 0.0,
  "sharpe_ratio": 0.0,
  "trades_count": 0,
  "win_rate": 0.0,
  "last_updated": "2026-07-08 13:17:00",
  "circuit_breaker_tripped": false,
  "circuit_breaker_date": "",
  "equity_curve": [
    {
      "date": "2026-07-01",
      "value": 32.33
    }
  ],
  "benchmark_curve": [],
  "trades": []
};